<?php
/**
 * Mission Data for Swarm Theme
 * Auto-generated by sync_missions_to_website.py
 * Last updated: 2026-01-16T01:07:18.616436
 */

$mission_data = {
  "master_task_log": [
    {
      "id": "mission_3",
      "title": "MEDIUM: M",
      "description": "M",
      "priority": "medium",
      "status": "pending",
      "agent": "Unknown",
      "points": 50,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "medium",
        "pending",
        "unknown"
      ],
      "raw_description": "M"
    },
    {
      "id": "mission_4",
      "title": "LOW: F",
      "description": "F",
      "priority": "low",
      "status": "pending",
      "agent": "Unknown",
      "points": 25,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "low",
        "pending",
        "unknown"
      ],
      "raw_description": "F"
    },
    {
      "id": "mission_5",
      "title": "MEDIUM: C",
      "description": "C",
      "priority": "medium",
      "status": "pending",
      "agent": "Unknown",
      "points": 40,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "medium",
        "pending",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_7",
      "title": "HIGH: I",
      "description": "I",
      "priority": "high",
      "status": "pending",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "high",
        "pending",
        "unknown"
      ],
      "raw_description": "I"
    },
    {
      "id": "mission_26",
      "title": "HIGH: C",
      "description": "C",
      "priority": "high",
      "status": "pending",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "high",
        "pending",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_27",
      "title": "HIGH: R",
      "description": "R",
      "priority": "high",
      "status": "pending",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "high",
        "pending",
        "unknown"
      ],
      "raw_description": "R"
    },
    {
      "id": "mission_34",
      "title": "HIGH: P",
      "description": "P",
      "priority": "high",
      "status": "pending",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "high",
        "pending",
        "unknown"
      ],
      "raw_description": "P"
    },
    {
      "id": "mission_42",
      "title": "HIGH: T",
      "description": "T",
      "priority": "high",
      "status": "pending",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "high",
        "pending",
        "unknown"
      ],
      "raw_description": "T"
    },
    {
      "id": "mission_45",
      "title": "HIGH: A",
      "description": "A",
      "priority": "high",
      "status": "pending",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "high",
        "pending",
        "unknown"
      ],
      "raw_description": "A"
    },
    {
      "id": "mission_46",
      "title": "HIGH: C",
      "description": "C",
      "priority": "high",
      "status": "pending",
      "agent": "Unknown",
      "points": 200,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "high",
        "pending",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_47",
      "title": "HIGH: C",
      "description": "C",
      "priority": "high",
      "status": "pending",
      "agent": "Unknown",
      "points": 300,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "high",
        "pending",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_48",
      "title": "HIGH: C",
      "description": "C",
      "priority": "high",
      "status": "pending",
      "agent": "Unknown",
      "points": 200,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "high",
        "pending",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_49",
      "title": "HIGH: C",
      "description": "C",
      "priority": "high",
      "status": "pending",
      "agent": "Unknown",
      "points": 300,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "high",
        "pending",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_50",
      "title": "MEDIUM: M",
      "description": "M",
      "priority": "medium",
      "status": "pending",
      "agent": "Unknown",
      "points": 50,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "medium",
        "pending",
        "unknown"
      ],
      "raw_description": "M"
    },
    {
      "id": "mission_52",
      "title": "LOW: W",
      "description": "W",
      "priority": "low",
      "status": "pending",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "low",
        "pending",
        "unknown"
      ],
      "raw_description": "W"
    },
    {
      "id": "mission_53",
      "title": "LOW: A",
      "description": "A",
      "priority": "low",
      "status": "pending",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "low",
        "pending",
        "unknown"
      ],
      "raw_description": "A"
    }
  ],
  "cycle_accomplishments": [
    {
      "id": "mission_1",
      "title": "HIGH: N",
      "description": "N",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 75,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "N"
    },
    {
      "id": "mission_2",
      "title": "MEDIUM: D",
      "description": "D",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 50,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "D"
    },
    {
      "id": "mission_6",
      "title": "HIGH: P",
      "description": "P",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 50,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "P"
    },
    {
      "id": "mission_8",
      "title": "HIGH: D",
      "description": "D",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "D"
    },
    {
      "id": "mission_9",
      "title": "HIGH: R",
      "description": "R",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "R"
    },
    {
      "id": "mission_10",
      "title": "HIGH: A",
      "description": "A",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "A"
    },
    {
      "id": "mission_11",
      "title": "HIGH: C",
      "description": "C",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_12",
      "title": "HIGH: P",
      "description": "P",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "P"
    },
    {
      "id": "mission_13",
      "title": "HIGH: U",
      "description": "U",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "U"
    },
    {
      "id": "mission_14",
      "title": "HIGH: S",
      "description": "S",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "S"
    },
    {
      "id": "mission_15",
      "title": "HIGH: [",
      "description": "[",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 100,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "["
    },
    {
      "id": "mission_16",
      "title": "MEDIUM: [",
      "description": "[",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 75,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "["
    },
    {
      "id": "mission_17",
      "title": "MEDIUM: [",
      "description": "[",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 75,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "["
    },
    {
      "id": "mission_18",
      "title": "HIGH: F",
      "description": "F",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "F"
    },
    {
      "id": "mission_19",
      "title": "HIGH: C",
      "description": "C",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_20",
      "title": "MEDIUM: C",
      "description": "C",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_21",
      "title": "HIGH: C",
      "description": "C",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_22",
      "title": "MEDIUM: V",
      "description": "V",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "V"
    },
    {
      "id": "mission_23",
      "title": "HIGH: C",
      "description": "C",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_24",
      "title": "MEDIUM: C",
      "description": "C",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_25",
      "title": "MEDIUM: C",
      "description": "C",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_28",
      "title": "HIGH: T",
      "description": "T",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "T"
    },
    {
      "id": "mission_29",
      "title": "HIGH: f",
      "description": "f",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "f"
    },
    {
      "id": "mission_30",
      "title": "CRITICAL: R",
      "description": "R",
      "priority": "critical",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "critical",
        "completed",
        "unknown"
      ],
      "raw_description": "R"
    },
    {
      "id": "mission_31",
      "title": "CRITICAL: T",
      "description": "T",
      "priority": "critical",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "critical",
        "completed",
        "unknown"
      ],
      "raw_description": "T"
    },
    {
      "id": "mission_32",
      "title": "HIGH: P",
      "description": "P",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "P"
    },
    {
      "id": "mission_33",
      "title": "HIGH: P",
      "description": "P",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "P"
    },
    {
      "id": "mission_35",
      "title": "MEDIUM: S",
      "description": "S",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "S"
    },
    {
      "id": "mission_36",
      "title": "MEDIUM: W",
      "description": "W",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "W"
    },
    {
      "id": "mission_37",
      "title": "MEDIUM: B",
      "description": "B",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "B"
    },
    {
      "id": "mission_38",
      "title": "MEDIUM: B",
      "description": "B",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "B"
    },
    {
      "id": "mission_39",
      "title": "MEDIUM: B",
      "description": "B",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "B"
    },
    {
      "id": "mission_40",
      "title": "MEDIUM: B",
      "description": "B",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "B"
    },
    {
      "id": "mission_41",
      "title": "MEDIUM: B",
      "description": "B",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "B"
    },
    {
      "id": "mission_43",
      "title": "MEDIUM: T",
      "description": "T",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "T"
    },
    {
      "id": "mission_44",
      "title": "HIGH: A",
      "description": "A",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "A"
    },
    {
      "id": "mission_51",
      "title": "HIGH: W",
      "description": "W",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "W"
    }
  ],
  "mission_history": [
    {
      "id": "mission_1",
      "title": "HIGH: N",
      "description": "N",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 75,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "N"
    },
    {
      "id": "mission_2",
      "title": "MEDIUM: D",
      "description": "D",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 50,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "D"
    },
    {
      "id": "mission_3",
      "title": "MEDIUM: M",
      "description": "M",
      "priority": "medium",
      "status": "pending",
      "agent": "Unknown",
      "points": 50,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "medium",
        "pending",
        "unknown"
      ],
      "raw_description": "M"
    },
    {
      "id": "mission_4",
      "title": "LOW: F",
      "description": "F",
      "priority": "low",
      "status": "pending",
      "agent": "Unknown",
      "points": 25,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "low",
        "pending",
        "unknown"
      ],
      "raw_description": "F"
    },
    {
      "id": "mission_5",
      "title": "MEDIUM: C",
      "description": "C",
      "priority": "medium",
      "status": "pending",
      "agent": "Unknown",
      "points": 40,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "medium",
        "pending",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_6",
      "title": "HIGH: P",
      "description": "P",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 50,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "P"
    },
    {
      "id": "mission_7",
      "title": "HIGH: I",
      "description": "I",
      "priority": "high",
      "status": "pending",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "high",
        "pending",
        "unknown"
      ],
      "raw_description": "I"
    },
    {
      "id": "mission_8",
      "title": "HIGH: D",
      "description": "D",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "D"
    },
    {
      "id": "mission_9",
      "title": "HIGH: R",
      "description": "R",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "R"
    },
    {
      "id": "mission_10",
      "title": "HIGH: A",
      "description": "A",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "A"
    },
    {
      "id": "mission_11",
      "title": "HIGH: C",
      "description": "C",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_12",
      "title": "HIGH: P",
      "description": "P",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "P"
    },
    {
      "id": "mission_13",
      "title": "HIGH: U",
      "description": "U",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "U"
    },
    {
      "id": "mission_14",
      "title": "HIGH: S",
      "description": "S",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "S"
    },
    {
      "id": "mission_15",
      "title": "HIGH: [",
      "description": "[",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 100,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "["
    },
    {
      "id": "mission_16",
      "title": "MEDIUM: [",
      "description": "[",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 75,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "["
    },
    {
      "id": "mission_17",
      "title": "MEDIUM: [",
      "description": "[",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 75,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "["
    },
    {
      "id": "mission_18",
      "title": "HIGH: F",
      "description": "F",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "F"
    },
    {
      "id": "mission_19",
      "title": "HIGH: C",
      "description": "C",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_20",
      "title": "MEDIUM: C",
      "description": "C",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_21",
      "title": "HIGH: C",
      "description": "C",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_22",
      "title": "MEDIUM: V",
      "description": "V",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "V"
    },
    {
      "id": "mission_23",
      "title": "HIGH: C",
      "description": "C",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_24",
      "title": "MEDIUM: C",
      "description": "C",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_25",
      "title": "MEDIUM: C",
      "description": "C",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_26",
      "title": "HIGH: C",
      "description": "C",
      "priority": "high",
      "status": "pending",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "high",
        "pending",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_27",
      "title": "HIGH: R",
      "description": "R",
      "priority": "high",
      "status": "pending",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "high",
        "pending",
        "unknown"
      ],
      "raw_description": "R"
    },
    {
      "id": "mission_28",
      "title": "HIGH: T",
      "description": "T",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "T"
    },
    {
      "id": "mission_29",
      "title": "HIGH: f",
      "description": "f",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "f"
    },
    {
      "id": "mission_30",
      "title": "CRITICAL: R",
      "description": "R",
      "priority": "critical",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "critical",
        "completed",
        "unknown"
      ],
      "raw_description": "R"
    },
    {
      "id": "mission_31",
      "title": "CRITICAL: T",
      "description": "T",
      "priority": "critical",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "critical",
        "completed",
        "unknown"
      ],
      "raw_description": "T"
    },
    {
      "id": "mission_32",
      "title": "HIGH: P",
      "description": "P",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "P"
    },
    {
      "id": "mission_33",
      "title": "HIGH: P",
      "description": "P",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "P"
    },
    {
      "id": "mission_34",
      "title": "HIGH: P",
      "description": "P",
      "priority": "high",
      "status": "pending",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "high",
        "pending",
        "unknown"
      ],
      "raw_description": "P"
    },
    {
      "id": "mission_35",
      "title": "MEDIUM: S",
      "description": "S",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "S"
    },
    {
      "id": "mission_36",
      "title": "MEDIUM: W",
      "description": "W",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "W"
    },
    {
      "id": "mission_37",
      "title": "MEDIUM: B",
      "description": "B",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "B"
    },
    {
      "id": "mission_38",
      "title": "MEDIUM: B",
      "description": "B",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "B"
    },
    {
      "id": "mission_39",
      "title": "MEDIUM: B",
      "description": "B",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "B"
    },
    {
      "id": "mission_40",
      "title": "MEDIUM: B",
      "description": "B",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "B"
    },
    {
      "id": "mission_41",
      "title": "MEDIUM: B",
      "description": "B",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "B"
    },
    {
      "id": "mission_42",
      "title": "HIGH: T",
      "description": "T",
      "priority": "high",
      "status": "pending",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "high",
        "pending",
        "unknown"
      ],
      "raw_description": "T"
    },
    {
      "id": "mission_43",
      "title": "MEDIUM: T",
      "description": "T",
      "priority": "medium",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "medium",
        "completed",
        "unknown"
      ],
      "raw_description": "T"
    },
    {
      "id": "mission_44",
      "title": "HIGH: A",
      "description": "A",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "A"
    },
    {
      "id": "mission_45",
      "title": "HIGH: A",
      "description": "A",
      "priority": "high",
      "status": "pending",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "high",
        "pending",
        "unknown"
      ],
      "raw_description": "A"
    },
    {
      "id": "mission_46",
      "title": "HIGH: C",
      "description": "C",
      "priority": "high",
      "status": "pending",
      "agent": "Unknown",
      "points": 200,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "high",
        "pending",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_47",
      "title": "HIGH: C",
      "description": "C",
      "priority": "high",
      "status": "pending",
      "agent": "Unknown",
      "points": 300,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "high",
        "pending",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_48",
      "title": "HIGH: C",
      "description": "C",
      "priority": "high",
      "status": "pending",
      "agent": "Unknown",
      "points": 200,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "high",
        "pending",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_49",
      "title": "HIGH: C",
      "description": "C",
      "priority": "high",
      "status": "pending",
      "agent": "Unknown",
      "points": 300,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "high",
        "pending",
        "unknown"
      ],
      "raw_description": "C"
    },
    {
      "id": "mission_50",
      "title": "MEDIUM: M",
      "description": "M",
      "priority": "medium",
      "status": "pending",
      "agent": "Unknown",
      "points": 50,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "medium",
        "pending",
        "unknown"
      ],
      "raw_description": "M"
    },
    {
      "id": "mission_51",
      "title": "HIGH: W",
      "description": "W",
      "priority": "high",
      "status": "completed",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 100,
      "tags": [
        "high",
        "completed",
        "unknown"
      ],
      "raw_description": "W"
    },
    {
      "id": "mission_52",
      "title": "LOW: W",
      "description": "W",
      "priority": "low",
      "status": "pending",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "low",
        "pending",
        "unknown"
      ],
      "raw_description": "W"
    },
    {
      "id": "mission_53",
      "title": "LOW: A",
      "description": "A",
      "priority": "low",
      "status": "pending",
      "agent": "Unknown",
      "points": 0,
      "execution_type": "Unknown",
      "completed_date": null,
      "date": "2026-01-16",
      "progress": 0,
      "tags": [
        "low",
        "pending",
        "unknown"
      ],
      "raw_description": "A"
    }
  ],
  "project_state": {
    "total_files": 1500,
    "total_loc": 125000,
    "active_components": 45,
    "health_indicators": [
      {
        "label": "Code Quality",
        "value": "95%",
        "status": "healthy"
      },
      {
        "label": "Test Coverage",
        "value": "87%",
        "status": "healthy"
      },
      {
        "label": "Documentation",
        "value": "92%",
        "status": "healthy"
      },
      {
        "label": "Performance",
        "value": "88%",
        "status": "healthy"
      }
    ],
    "active_agents": 8,
    "current_phase": "V2 Implementation",
    "last_updated": "2026-01-16T01:07:18.616436"
  },
  "metadata": {
    "last_updated": "2026-01-16T01:07:18.616436",
    "source_file": "D:\\Agent_Cellphone_V2_Repository\\MASTER_TASK_LOG.md",
    "parser_version": "2.0.0"
  },
  "stats": {
    "total_missions": 53,
    "completed_missions": 37,
    "pending_missions": 16,
    "completion_rate": 69.8,
    "agents_involved": 0,
    "total_points": 425
  }
};
$mission_history = $mission_data['mission_history'];
$mission_stats = $mission_data['stats'];
$current_missions = $mission_data['master_task_log'];
$completed_missions = $mission_data['cycle_accomplishments'];
