<?php
/**
 * Admin Daily Plans Page Template
 */

if (!defined('ABSPATH')) {
    exit;
}

$db = new FRATP_Database();
$symbols = explode(',', get_option('fratp_stock_symbols', 'TSLA'));
$symbols = array_map('trim', $symbols);

// Get latest plans for each symbol
$plans = array();
foreach ($symbols as $symbol) {
    $plan = $db->get_latest_plan($symbol);
    if ($plan) {
        $plans[] = $plan;
    }
}
?>

<div class="wrap">
    <h1><?php echo esc_html(get_admin_page_title()); ?></h1>
    
    <p><?php _e('View and manage daily trading plans generated by the automated system.', 'freeride-automated-trading-plan'); ?></p>
    
    <?php if (empty($plans)): ?>
        <div class="notice notice-info">
            <p><?php _e('No trading plans found. Plans are generated automatically via cron job or can be generated manually from Settings.', 'freeride-automated-trading-plan'); ?></p>
        </div>
    <?php else: ?>
        <div class="fratp-plans-list">
            <?php foreach ($plans as $plan): ?>
                <div class="fratp-plan-card">
                    <h2><?php echo esc_html($plan['symbol']); ?> - <?php echo esc_html($plan['date']); ?></h2>
                    
                    <div class="fratp-plan-meta">
                        <span><strong><?php _e('Price:', 'freeride-automated-trading-plan'); ?></strong> $<?php echo number_format($plan['current_price'], 2); ?></span>
                        <span><strong><?php _e('Signal:', 'freeride-automated-trading-plan'); ?></strong> 
                            <span class="fratp-signal-<?php echo esc_attr($plan['signal']); ?>">
                                <?php echo strtoupper(esc_html($plan['signal'])); ?>
                            </span>
                        </span>
                        <span><strong><?php _e('RSI:', 'freeride-automated-trading-plan'); ?></strong> <?php echo number_format($plan['rsi'], 2); ?></span>
                    </div>
                    
                    <div class="fratp-plan-recommendation">
                        <p><?php echo esc_html($plan['recommendation']); ?></p>
                    </div>
                    
                    <?php if (isset($plan['trade'])): ?>
                        <div class="fratp-plan-trade">
                            <h3><?php _e('Trade Details', 'freeride-automated-trading-plan'); ?></h3>
                            <ul>
                                <li><?php _e('Direction:', 'freeride-automated-trading-plan'); ?> <strong><?php echo strtoupper(esc_html($plan['trade']['direction'])); ?></strong></li>
                                <li><?php _e('Entry:', 'freeride-automated-trading-plan'); ?> <strong>$<?php echo number_format($plan['trade']['entry_price'], 2); ?></strong></li>
                                <li><?php _e('Stop Loss:', 'freeride-automated-trading-plan'); ?> <strong>$<?php echo number_format($plan['trade']['stop_loss'], 2); ?></strong></li>
                                <li><?php _e('Target:', 'freeride-automated-trading-plan'); ?> <strong>$<?php echo number_format($plan['trade']['profit_target'], 2); ?></strong></li>
                                <li><?php _e('Size:', 'freeride-automated-trading-plan'); ?> <strong><?php echo number_format($plan['trade']['position_size']); ?> <?php _e('shares', 'freeride-automated-trading-plan'); ?></strong></li>
                            </ul>
                        </div>
                    <?php endif; ?>
                    
                    <div class="fratp-plan-actions">
                        <a href="<?php echo admin_url('admin.php?page=fratp-view-plan&symbol=' . urlencode($plan['symbol']) . '&date=' . urlencode($plan['date'])); ?>" class="button">
                            <?php _e('View Full Plan', 'freeride-automated-trading-plan'); ?>
                        </a>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    
    <hr>
    
    <h2><?php _e('Generate New Plan', 'freeride-automated-trading-plan'); ?></h2>
    <form id="fratp-generate-plan-form">
        <?php wp_nonce_field('fratp_nonce', 'nonce'); ?>
        <select name="symbol" required>
            <?php foreach ($symbols as $symbol): ?>
                <option value="<?php echo esc_attr($symbol); ?>"><?php echo esc_html($symbol); ?></option>
            <?php endforeach; ?>
        </select>
        <button type="submit" class="button button-primary"><?php _e('Generate Plan', 'freeride-automated-trading-plan'); ?></button>
    </form>
    <div id="fratp-generate-result" style="margin-top: 20px;"></div>
</div>

<script>
jQuery(document).ready(function($) {
    $('#fratp-generate-plan-form').on('submit', function(e) {
        e.preventDefault();
        var $form = $(this);
        var $result = $('#fratp-generate-result');
        
        $result.html('<p>Generating plan...</p>');
        
        $.ajax({
            url: ajaxurl,
            type: 'POST',
            data: {
                action: 'fratp_generate_plan',
                nonce: $form.find('[name="nonce"]').val(),
                symbol: $form.find('[name="symbol"]').val()
            },
            success: function(response) {
                if (response.success) {
                    $result.html('<div class="notice notice-success"><p>Plan generated successfully! <a href="' + window.location.href + '">Refresh page to view.</a></p></div>');
                } else {
                    $result.html('<div class="notice notice-error"><p>' + response.data.message + '</p></div>');
                }
            },
            error: function() {
                $result.html('<div class="notice notice-error"><p>Error generating plan.</p></div>');
            }
        });
    });
});
</script>

