<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
    <meta charset="<?php bloginfo('charset'); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#0a0a1a">
    <link rel="profile" href="https://gmpg.org/xfn/11">
    
    <!-- Google Fonts for Cosmic Theme -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;500;600;700;800;900&family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    
    <?php wp_head(); ?>
</head>

<body <?php body_class(); ?>>
<?php wp_body_open(); ?>

<!-- Cosmic Background Elements -->
<div class="cosmic-bg"></div>

<!-- Animated Nebula Clouds -->
<div class="nebula nebula-1"></div>
<div class="nebula nebula-2"></div>
<div class="nebula nebula-3"></div>

<!-- Animated Stars Container (Stars generated by JavaScript) -->
<div class="stars-layer" id="stars-container"></div>

<!-- Shooting Stars -->
<div class="shooting-star" style="top: 10%; left: 0; animation-delay: 0s;"></div>
<div class="shooting-star" style="top: 30%; left: 10%; animation-delay: 2s;"></div>
<div class="shooting-star" style="top: 5%; left: 20%; animation-delay: 4s;"></div>

<div id="page" class="site">
    <header id="masthead" class="site-header">
        <div class="container">
            <div class="site-branding">
                <?php if (has_custom_logo()) : ?>
                    <div class="site-logo">
                        <?php the_custom_logo(); ?>
                    </div>
                <?php else : ?>
                    <h1 class="site-title">
                        <a href="<?php echo esc_url(home_url('/')); ?>" rel="home">
                            <span class="logo-icon">🚀</span>
                            <?php bloginfo('name'); ?>
                        </a>
                    </h1>
                <?php endif; ?>
                
                <?php
                $description = get_bloginfo('description', 'display');
                if ($description || is_customize_preview()) :
                ?>
                    <p class="site-description"><?php echo $description; ?></p>
                <?php endif; ?>
            </div>
            
            <button class="nav-toggle" aria-label="<?php esc_attr_e('Toggle Navigation', 'ariajet-cosmic'); ?>" aria-expanded="false">
                <span></span>
                <span></span>
                <span></span>
            </button>
            
            <nav id="site-navigation" class="main-navigation" aria-label="<?php esc_attr_e('Primary Navigation', 'ariajet-cosmic'); ?>">
                <?php
                if (has_nav_menu('primary')) {
                    wp_nav_menu(array(
                        'theme_location' => 'primary',
                        'menu_id' => 'primary-menu',
                        'container' => false,
                    ));
                } else {
                    // Default menu for when no menu is assigned
                    ?>
                    <ul id="primary-menu">
                        <li><a href="<?php echo esc_url(home_url('/')); ?>"><?php _e('Home', 'ariajet-cosmic'); ?></a></li>
                        <li><a href="<?php echo esc_url(home_url('/games/')); ?>"><?php _e('Games', 'ariajet-cosmic'); ?></a></li>
                        <li><a href="<?php echo esc_url(home_url('/about/')); ?>"><?php _e('About', 'ariajet-cosmic'); ?></a></li>
                    </ul>
                    <?php
                }
                ?>
            </nav>
        </div>
    </header>
