#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail

echo "== WIRE SCORING TO DISCORD SHEET =="

python - << 'PY'
from pathlib import Path

p = Path("apps/discord-bot/src/index.js")
s = p.read_text()

s = s.replace(
"""import {
  interpretQuizResult
} from '../../../packages/aegis-interpreter/index.js';""",
"""import {
  interpretQuizResult
} from '../../../packages/aegis-interpreter/index.js';

import {
  buildCharacterSheet
} from '../../../packages/scoring-engine/index.js';

import fs from 'node:fs';
import path from 'node:path';"""
)

s = s.replace(
"""function buildResultsEmbed(user, session, aegis = null) {""",
"""function saveCharacterSheet(userId, sheet) {
  const outDir = path.resolve(new URL('../../..', import.meta.url).pathname, 'data/state/character_sheets');
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, `${userId}.json`), JSON.stringify(sheet, null, 2) + '\\n');
}

function buildSheetEmbed(user, sheet, aegis = null) {
  return new EmbedBuilder()
    .setTitle('AEGIS Character Sheet Locked')
    .setDescription(
      `Subject: **${user.username}**\\n` +
      `Domain: **${sheet.primary_domain.toUpperCase()}**\\n` +
      `Tier: **${sheet.tier}**\\n` +
      `Threat Class: **${sheet.threat_class}**`
    )
    .addFields(
      { name: 'Domain Scores', value: Object.entries(sheet.domain_scores).map(([k,v]) => `**${k}**: ${v}`).join('\\n'), inline: true },
      { name: 'Flavor Vectors', value: Object.entries(sheet.flavor_vectors).map(([k,v]) => `**${k}**: ${v}`).join('\\n'), inline: true },
      { name: 'Manifestation', value: sheet.manifestation.descriptor, inline: false }
    )
    .setColor(0xf1c40f)
    .setFooter({ text: 'Immutable sheet generated by Spark Protocol.' });
}

function buildResultsEmbed(user, session, aegis = null) {"""
)

s = s.replace(
"""      const aegisPacket = await interpretQuizResult({
        quiz,
        responses: session.responses,
        results
      });

      saveQuizResult(interaction.user.id, {
        user_id: interaction.user.id,
        username: interaction.user.username,
        submitted_at: new Date().toISOString(),
        responses: session.responses,
        results,
        aegis: aegisPacket
      });

      await interaction.update({
        embeds: [buildResultsEmbed(interaction.user, session, aegisPacket.interpretation)],
        components: []
      });""",
"""      const sheet = buildCharacterSheet({
        userId: interaction.user.id,
        username: interaction.user.username,
        responses: session.responses
      });

      const aegisPacket = await interpretQuizResult({
        quiz,
        responses: session.responses,
        results
      });

      saveCharacterSheet(interaction.user.id, sheet);

      saveQuizResult(interaction.user.id, {
        user_id: interaction.user.id,
        username: interaction.user.username,
        submitted_at: new Date().toISOString(),
        responses: session.responses,
        results,
        sheet,
        aegis: aegisPacket
      });

      await interaction.update({
        embeds: [buildSheetEmbed(interaction.user, sheet, aegisPacket.interpretation)],
        components: []
      });"""
)

p.write_text(s)
print("BOT_SCORING_WIRED=PASS")
PY

cat > tests/e2e/scored_sheet_flow.e2e.test.js << 'JS'
import assert from 'node:assert/strict';
import test from 'node:test';

import {
  loadQuiz,
  normalizeQuestion,
  buildBasicResults
} from '../../packages/quiz-engine/index.js';

import {
  buildCharacterSheet
} from '../../packages/scoring-engine/index.js';

test('e2e scored sheet flow builds locked deterministic sheet after 72 answers', () => {
  const quiz = loadQuiz();
  const responses = {};

  quiz.questions.forEach((question, index) => {
    const normalized = normalizeQuestion(question, index);
    responses[normalized.id] = index < 36 ? 'C' : 'F';
  });

  const results = buildBasicResults(quiz, responses);
  assert.equal(results.locked, true);

  const sheet = buildCharacterSheet({
    userId: '150',
    username: 'TheEmergenceTest',
    responses
  });

  assert.equal(sheet.schema_version, 'spark_character_sheet_v1');
  assert.equal(sheet.locked, true);
  assert.equal(sheet.primary_domain, 'velocity');
  assert.equal(sheet.primary_score, 36);
  assert.equal(sheet.tier, 'T5');
  assert.equal(sheet.threat_class, 'ALPHA');
  assert.equal(sheet.domain_scores.velocity, 36);
  assert.equal(sheet.flavor_vectors.stealth, 36);
});
JS

npm run test:mobile
node --test tests/e2e/scored_sheet_flow.e2e.test.js

echo "WIRE_SCORING_TO_DISCORD_SHEET=PASS"
