#!/usr/bin/env python3
"""
WordPress Analytics Tracking Deployment Tool
============================================

Deploys GA4 and Facebook Pixel tracking codes to WordPress themes
via functions.php wp_head hook.

Supports:
- GA4 tracking code deployment
- Facebook Pixel code deployment
- Custom event tracking configuration
- Batch deployment across multiple sites
"""

import json
import re
import os
from pathlib import Path
from typing import Dict, List, Optional
from datetime import datetime

# Website to theme path mapping
WEBSITE_THEME_PATHS = {
    "crosbyultimateevents.com": "websites/crosbyultimateevents.com/wp/wp-content/themes",
    "dadudekc.com": "websites/dadudekc.com/wp/wp-content/themes",
    "freerideinvestor.com": "websites/freerideinvestor.com/wp/wp-content/themes",
    "houstonsipqueen.com": "websites/houstonsipqueen.com/wp/wp-content/themes",
    "tradingrobotplug.com": "websites/tradingrobotplug.com/wp/wp-content/themes",
}

ANALYTICS_SETUP_DIR = Path("docs/analytics_setup")


def read_tracking_code(file_path: Path) -> str:
    """Read tracking code from HTML file."""
    if not file_path.exists():
        return ""
    return file_path.read_text(encoding="utf-8").strip()


def convert_html_to_php_output(html_code: str) -> str:
    """Convert HTML tracking code to PHP echo output."""
    # Escape quotes and convert to PHP echo statements
    lines = html_code.split("\n")
    php_lines = []
    
    for line in lines:
        line = line.strip()
        if not line:
            continue
        # Escape single quotes for PHP
        escaped_line = line.replace("'", "\\'")
        # Escape dollar signs (for PHP variables)
        escaped_line = escaped_line.replace("$", "\\$")
        php_lines.append(f"        echo '{escaped_line}\\n';")
    
    return "\n".join(php_lines)


def generate_analytics_function(ga4_code: str, pixel_code: str) -> str:
    """Generate PHP function to output analytics tracking codes."""
    ga4_php = convert_html_to_php_output(ga4_code)
    pixel_php = convert_html_to_php_output(pixel_code)
    
    return f"""/**
 * Add Google Analytics 4 and Facebook Pixel tracking codes
 * Generated by batch_analytics_setup.py
 */
function add_analytics_tracking_codes() {{
    // Google Analytics 4 (GA4)
{ga4_php}
    
    // Facebook Pixel
{pixel_php}
}}
add_action('wp_head', 'add_analytics_tracking_codes', 99);"""


def find_active_theme_path(website_path: Path) -> Optional[Path]:
    """Find the active theme directory in WordPress."""
    themes_dir = website_path
    if not themes_dir.exists():
        return None
    
    # List theme directories
    theme_dirs = [d for d in themes_dir.iterdir() if d.is_dir() and not d.name.startswith(".")]
    
    if not theme_dirs:
        return None
    
    # Check for common theme names or use first available
    # In practice, you might need to check wp-config.php or database for active theme
    # For now, return the first theme directory found
    return theme_dirs[0] if theme_dirs else None


def find_functions_php(theme_path: Path) -> Path:
    """Find or create functions.php in theme directory."""
    functions_file = theme_path / "functions.php"
    return functions_file


def add_analytics_to_functions_php(functions_file: Path, analytics_function: str) -> bool:
    """Add analytics function to functions.php, avoiding duplicates."""
    # Read existing functions.php
    existing_content = ""
    if functions_file.exists():
        existing_content = functions_file.read_text(encoding="utf-8")
        
        # Check if analytics function already exists
        if "add_analytics_tracking_codes" in existing_content:
            print(f"  ⚠️  Analytics tracking already exists in {functions_file.name}")
            return False
    
    # Append analytics function
    new_content = existing_content
    if new_content and not new_content.endswith("\n"):
        new_content += "\n"
    new_content += "\n" + analytics_function + "\n"
    
    # Write back
    functions_file.write_text(new_content, encoding="utf-8")
    return True


def deploy_analytics_for_website(domain: str, project_root: Path) -> Dict:
    """Deploy analytics tracking for a single website."""
    result = {
        "domain": domain,
        "status": "pending",
        "ga4_deployed": False,
        "pixel_deployed": False,
        "errors": [],
    }
    
    try:
        # Find analytics setup files
        setup_dir = project_root / ANALYTICS_SETUP_DIR / domain
        ga4_file = setup_dir / "ga4_tracking_code.html"
        pixel_file = setup_dir / "facebook_pixel_code.html"
        
        if not ga4_file.exists() or not pixel_file.exists():
            result["errors"].append(f"Analytics setup files not found for {domain}")
            result["status"] = "failed"
            return result
        
        # Read tracking codes
        ga4_code = read_tracking_code(ga4_file)
        pixel_code = read_tracking_code(pixel_file)
        
        if not ga4_code or not pixel_code:
            result["errors"].append(f"Empty tracking code files for {domain}")
            result["status"] = "failed"
            return result
        
        # Find theme path
        theme_base_path = project_root / WEBSITE_THEME_PATHS.get(domain, "")
        if not theme_base_path.exists():
            result["errors"].append(f"Theme directory not found: {theme_base_path}")
            result["status"] = "skipped"
            return result
        
        # Find active theme
        theme_path = find_active_theme_path(theme_base_path)
        if not theme_path:
            result["errors"].append(f"No theme found in {theme_base_path}")
            result["status"] = "skipped"
            return result
        
        # Find functions.php
        functions_file = find_functions_php(theme_path)
        
        # Generate analytics function
        analytics_function = generate_analytics_function(ga4_code, pixel_code)
        
        # Add to functions.php
        if add_analytics_to_functions_php(functions_file, analytics_function):
            result["ga4_deployed"] = True
            result["pixel_deployed"] = True
            result["status"] = "success"
            result["functions_file"] = str(functions_file.relative_to(project_root))
        else:
            result["status"] = "skipped"
            result["errors"].append("Analytics already exists in functions.php")
    
    except Exception as e:
        result["status"] = "error"
        result["errors"].append(str(e))
    
    return result


def deploy_analytics_batch(websites: Optional[List[str]] = None) -> Dict:
    """Deploy analytics tracking for multiple websites."""
    project_root = Path(__file__).parent.parent
    
    if websites is None:
        websites = list(WEBSITE_THEME_PATHS.keys())
    
    results = {
        "timestamp": datetime.now().strftime("%Y%m%d_%H%M%S"),
        "websites": {},
        "summary": {
            "total": len(websites),
            "success": 0,
            "skipped": 0,
            "failed": 0,
        },
    }
    
    print(f"🚀 Starting Analytics Tracking Deployment...")
    print(f"📊 Processing {len(websites)} websites...\n")
    
    for domain in websites:
        print(f"📁 Processing {domain}...")
        result = deploy_analytics_for_website(domain, project_root)
        results["websites"][domain] = result
        
        if result["status"] == "success":
            results["summary"]["success"] += 1
            print(f"  ✅ Analytics deployed to {result['functions_file']}")
        elif result["status"] == "skipped":
            results["summary"]["skipped"] += 1
            print(f"  ⚠️  {result['errors'][0] if result['errors'] else 'Skipped'}")
        else:
            results["summary"]["failed"] += 1
            print(f"  ❌ Failed: {', '.join(result['errors'])}")
    
    # Save deployment report
    report_file = project_root / "docs" / "analytics_setup" / f"deployment_report_{results['timestamp']}.json"
    report_file.parent.mkdir(parents=True, exist_ok=True)
    report_file.write_text(json.dumps(results, indent=2), encoding="utf-8")
    
    print(f"\n✅ Deployment complete!")
    print(f"📊 Summary:")
    print(f"   Success: {results['summary']['success']}")
    print(f"   Skipped: {results['summary']['skipped']}")
    print(f"   Failed: {results['summary']['failed']}")
    print(f"\n📄 Report saved: {report_file.relative_to(project_root)}")
    
    return results


if __name__ == "__main__":
    import sys
    
    # Allow specifying websites via command line
    websites = sys.argv[1:] if len(sys.argv) > 1 else None
    
    results = deploy_analytics_batch(websites)
    
    # Exit with error code if any failures
    if results["summary"]["failed"] > 0:
        sys.exit(1)

